version: 2

workflows:
  version: 2
  commit-build:
    jobs:
      - document
      - doctest
      - tests-python38
      - tests-python37
      - tests-python36
      - tests-rdbstorage

jobs:

  document:
    docker:
      - image: readthedocs/build:latest
    steps:
      - checkout

      - run: &checkout-merge-master
          name: checkout-merge-master
          command: |
            set -ex
            if [[ -n "${CIRCLE_PR_NUMBER}" ]]; then
                FETCH_REFS="${FETCH_REFS} +refs/pull/${CIRCLE_PR_NUMBER}/merge:pr/${CIRCLE_PR_NUMBER}/merge"
                git fetch -u origin ${FETCH_REFS}
                git checkout "pr/${CIRCLE_PR_NUMBER}/merge"
            fi

      - run:
          name: install
          command: |
            python -m venv venv || virtualenv venv --python=python3.8
            . venv/bin/activate
            pip install -U pip
            pip install --progress-bar off .[document]

      - run:
          name: build
          command: |
            . venv/bin/activate
            cd docs
            make html

      - store_artifacts:
          path: ./docs/build/html

  doctest:
    docker:
      - image: readthedocs/build:latest
    steps:
      - checkout

      - run: *checkout-merge-master

      - run:
          name: install
          command: |
            python -m venv venv || virtualenv venv --python=python3
            . venv/bin/activate
            pip install -U pip
            pip install --progress-bar off .[doctest,document]

      - run:
          name: build
          command: |
            . venv/bin/activate
            cd docs
            make doctest

  tests-rdbstorage:
    docker:
      - image: circleci/python:3.7
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: optunatest
          MYSQL_USER: user
          MYSQL_PASSWORD: test
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: user
          POSTGRES_DB: optunatest
          POSTGRES_PASSWORD: test
    steps:
      - checkout

      - run: *checkout-merge-master

      - run: *install

      - run: &install-rdb-bindings
          name: install-rdb-bindings
          command: |
            . venv/bin/activate
            pip install --progress-bar off PyMySQL cryptography psycopg2-binary

      - run: &tests-mysql
          name: tests-mysql
          command: |
            . venv/bin/activate
            pytest tests/storages_tests/rdb_tests/test_with_server.py
          environment:
            OMP_NUM_THREADS: 1
            TEST_DB_URL: mysql+pymysql://user:test@127.0.0.1/optunatest

      - run: &tests-postgresql
          name: tests-postgresql
          command: |
            . venv/bin/activate
            pytest tests/storages_tests/rdb_tests/test_with_server.py
          environment:
            OMP_NUM_THREADS: 1
            TEST_DB_URL: postgresql+psycopg2://user:test@127.0.0.1/optunatest
