name: Coverage

on:
  push:
    branches:
      - master
  pull_request: {}
  schedule:
    - cron: '0 23 * * SUN-THU'

jobs:
  coverage:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Not intended for forks.
    if: github.repository == 'optuna/optuna'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Setup cache
      uses: actions/cache@v2
      env:
        cache-name: coverage
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/setup.py') }}-v1
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/setup.py') }}

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get -y install openmpi-bin libopenmpi-dev

    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install --progress-bar off -U setuptools

        # Install minimal dependencies and confirm that `import optuna` is successful.
        pip install --progress-bar off .
        python -c 'import optuna'
        optuna --version

        pip install --progress-bar off .[tests]
        pip install --progress-bar off .[optional]
        pip install --progress-bar off .[integration] -f https://download.pytorch.org/whl/torch_stable.html
        pip install --progress-bar off .[codecov]

        # Required for samplers_tests/test_samplers.py.
        # TODO(hvy): Fix samplers_tests/test_samplers.py to not require optional dependencies and remove these installs.
        pip install scikit-optimize
        pip install cma

    - name: Tests
      run: |
        pytest --cov=optuna --cov-report=xml tests

    - name: Tests MPI
      run: |
        mpirun -n 2 -- pytest tests/integration_tests/test_chainermn.py
      env:
        OMP_NUM_THREADS: 1

    - name: Codecov
      uses: codecov/codecov-actions@v1
